### ISSUE TITLE
Exception during conversion data 

### ISSUE THREAD

**Issue by tloczekt** [paul1956/CareLink#3]
I have a problem with language format of numbers....
" Conversion from string " 213.275" to type "Double" is not valid.
This is error for real data and test sample data as well. I think it comes from my own national local (polish) decimal pointer settings. In my case comma is a decimal pointer not dot. 

It related with float values like:
 reservoirRemainingUnits 213.275
"maxAutoBasalRate": 2.0,
  "maxBolusAmount": 10.0,
  "averageSGFloat": 123.38095

so some Functions GetDecimalValues in MathExtensions.vb, Form1.vb should be reviewed and more universal.

Situation is more complicated because in your case comma sign is already used as json data delimeter

More details on attached file
[exception.txt](https://github.com/paul1956/CareLink/files/9038623/exception.txt)
.

**Comment by paul1956** [comment]
@tloczekt This should be fixed in version 3.3 I uploaded today. Please report if it is not.

**Comment by paul1956** [comment]
@tloczekt it turns out the source data is always English, US and now I should override all the conversions. The output should be local.

**Comment by tloczekt** [comment]
Hi, 
@paul1956 thank you so much for your soon response and new release. It's better, I can see data on display, but curve of BG on HOME Page is missing, so BG data are still bad in conversion:  System.FormatException: Input string was not in a correct format. Its interesting because on Runing ActiveInsulin tab curve of insulin and BGs  are visible. 
Other data like present BG, TIR, sensor, vial %, Carbs are OK.
Information of bolus and meals are also ok.
 
[exception2.txt](https://github.com/paul1956/CareLink/files/9083595/exception2.txt)

**Comment by paul1956** [comment]
I think all those issues are fixed in 3.4.0.0 but I don’t have a stable internet connection to upload it.  I will try again Thursday if I can’t get it uploaded today otherwise it will be Monday.

 

If you are not in 100% scaling I am having issues painting some of the data the newest release should be better.

**Comment by tloczekt** [comment]
3.4.0.0 is step back for me, because again I have none data from the cloud, because String to datetime conversion error.
(System.FormatException: String '13.07.2022 00:01:00' was not recognized as a valid DateTime.)
More details in attached file.
[exception3.txt](https://github.com/paul1956/CareLink/files/9099157/exception3.txt)

**Comment by BenoitVDBr** [comment]
Hello Paul,

great development. I'm trying to use it on my 780G pump and the one from my son. I do however get an error (same as above) at login.

![error](https://user-images.githubusercontent.com/109212911/178703557-d5f9a2a8-eb13-40be-bfc0-d400bac0a777.jpg)

The full description in attachment.

[Unhandled Exception.txt](https://github.com/paul1956/CareLink/files/9100969/Unhandled.Exception.txt)

**Comment by paul1956** [comment]
@tloczekt @BenoitVDBr Thanks for the report, I believe the current version will handle this better in version 3.4.0.2 x64. It turns out that a few dates in the files are localized while most are in US-eng culture. I now try both formats when converting dates and I should also display in local culture with a few exceptions where the data is actually a string that just looks like a date. I am going to leave this open until you both verify it is fixed the two issues are actually different. Also, some of the data being truncated had to do with internally using a comma as a field separator and when numbers have a comma it breaks the algorithm.

**Comment by BenoitVDBr** [comment]
Hello Paul,

Thanks for the quick response. I tried the newest version, but the same problem persists. I do however see that the last SG value (upper left of the window) is retrieved correctly from the Carelink server. In the Active Insulin tab, the correct amount is displayed. Due to the error I don't see anything in the graph screens and I get "???" instead of values under the different icons. The TIR values aren't retrieved correctly.

![image](https://user-images.githubusercontent.com/109212911/179069615-67fd3b17-0434-4259-a9a2-057ae3150446.png)

I don't know if the new description brings any new info...

[Unhandled Exception 2.txt](https://github.com/paul1956/CareLink/files/9114848/Unhandled.Exception.2.txt)


Wkr,
Benoit.

**Comment by tloczekt** [comment]
Hello Paul,
version 3.4.03 x64 seems OK. We have all data and software started without any error message.
Main graph is visible as well. Thank you very much for your soon response and hard work. 
![screenshot](https://user-images.githubusercontent.com/71193996/179075754-5b9f9cba-87bf-4929-b19f-a08bd5e1b5b8.jpg)

**Comment by BenoitVDBr** [comment]
It works, it works, it works!!

Thank you very much!
